// <auto-generated />
namespace FCourse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixdbn2thtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixdbn2thtime));
        
        string IMigrationMetadata.Id
        {
            get { return "202206040821532_fix-db-n+2th-time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
